<!--
  Customize your build: https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022.
  See more MSBuild properties here: https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022.
-->
<Project>
    <PropertyGroup>
        <!--
          Sets up property "Treat warnings as errors" found in Visual Studio project -> Properties -> Build.
        -->
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

        <!--
          Sets up property "Language version" found in Visual Studio project -> Properties -> Build -> Advanced.
        -->
        <LangVersion>14.0</LangVersion>

        <!--
            Fix issue: "error NU1403: Package content hash validation failed for ..." occurring when restoring NuGet
            packages when using lock files.
            See more about the fix here: https://github.com/NuGet/Home/issues/7921#issuecomment-478152479.
        -->
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RestoreLockedMode>true</RestoreLockedMode>
        <NoWarn>NU1603;NU1902;NU1903</NoWarn>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    </PropertyGroup>

    <!--
    OSS license check required by Verify NuGet package starting with v33.1.0, released on September 19th, 2026.
    The below properties were generated folowing the instructions found here: https://github.com/VerifyTests/Verify#open-source-maintenance-fee.
    -->
    <PropertyGroup>
        <Verify_SponsorshipExemption>OpenSource</Verify_SponsorshipExemption>
        <Verify_SponsorshipExemptionUntil>2027-09</Verify_SponsorshipExemptionUntil>
    </PropertyGroup>
    
</Project>
