namespace Todo.ApplicationFlows.TodoItems
{
    using System;
    using System.Security.Principal;
    using System.Threading.Tasks;

    using Commons.ApplicationEvents;

    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Logging;

    using Persistence;

    /// <summary>
    /// Runs database migrations during application started event.
    /// </summary>
    public class RunDatabaseMigrations : IApplicationStartedEventListener
    {
        private const string FlowName = "Events/ApplicationStarted/RunDatabaseMigrations";
        private static readonly IPrincipal Principal = new GenericPrincipal(new GenericIdentity("run-database-migrations"), Array.Empty<string>());

        private readonly TodoDbContext todoDbContext;
        private readonly IConfiguration configuration;
        private readonly ILogger logger;

        /// <summary>
        /// Creates a new instance of the <see cref="RunDatabaseMigrations"/> class.
        /// </summary>
        /// <param name="todoDbContext">The EF Core DbContext to use when running database migrations.</param>
        /// <param name="configuration">Application configuration.</param>
        /// <param name="logger">Logs events generated by this instance.</param>
        /// <exception cref="ArgumentNullException">Thrown in case any of the above parameters is null.</exception>
        public RunDatabaseMigrations(TodoDbContext todoDbContext, IConfiguration configuration, ILogger<RunDatabaseMigrations> logger)
        {
            this.todoDbContext = todoDbContext ?? throw new ArgumentNullException(nameof(todoDbContext));
            this.configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Runs existing database migrations.
        /// </summary>
        public async Task OnApplicationStartedAsync()
        {
            await SimpleApplicationFlow.ExecuteAsync(FlowName, InternalRunDatabaseMigrationsAsync, Principal, logger);
        }

        private async Task InternalRunDatabaseMigrationsAsync()
        {
            string databaseName = "<unknown>";

            try
            {
                databaseName = todoDbContext.Database.GetDbConnection().Database;

                // ReSharper disable once SettingNotFoundInConfiguration
                bool shouldMigrateDatabase = configuration.GetValue<bool>("MigrateDatabase");

                if (shouldMigrateDatabase is false)
                {
                    logger.LogInformation("Migrating database has been turned off");

                    return;
                }

                bool shouldDeleteDatabase = configuration.GetValue<bool>("DeleteDatabaseBeforeRunningMigrations");

                if (shouldDeleteDatabase)
                {
                    logger.LogInformation("About to delete database {DatabaseName} ...", databaseName);
                    await todoDbContext.Database.EnsureDeletedAsync();
                    logger.LogInformation("Database {DatabaseName} has been deleted", databaseName);
                }

                logger.LogInformation("About to migrate database {DatabaseName} ...", databaseName);
                await todoDbContext.Database.MigrateAsync();
                logger.LogInformation("Database {DatabaseName} has been migrated successfully", databaseName);
            }
            catch (Exception exception)
            {
                logger.LogCritical(exception, "Failed to migrate database {DatabaseName}", databaseName);
                throw;
            }
        }
    }
}
